version: 2.1

jobs:
  get-the-code:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run:
          name: run the project
          command: npm start

      - run:
          name: test the project
          command: npm test
