version: 2.1

jobs:
  build:
    docker: #use docker executor
      - image: node:latest
    steps:
      - checkout
      - run:
          name: install dependencies
          command: npm install
  deploy:
    docker:
      - image: node:latest
    steps:
      - run:
          name: run the project
          command: npm start
      # - run:
      #     name: run the project
      #     command: npm start

      # - run:
      #     name: test the project
      #     command: npm test

      # - run:
      #     name: test the context
      #     command: echo $NAME
workflows:
  build_and_test:
    jobs:
      - build
      - deploy
