version: 2.1

executors:
  docker-executor:
    docker:
      - image: node:latest
    working_directory: /myApp

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package-lock.json" }}
            - v1-deps # will get the most recent cache
      - run:
          name: show all directories
          command: ls

      - run:
          name: install dependencies
          command: npm install

      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - persist_to_workspace:
          root: /myApp
          paths:
            - ./**

  deploy:
    executor: docker-executor
    steps:
      - attach_workspace:
          at: /myApp
      - run:
          name: list all directories
          command: ls
      - run:
          name: run the project
          command: npm start

workflows:
  build_and_test:
    jobs:
      - build
      - deploy:
          requires:
          - build
