version: 2.1

executors:
  docker-executor:
    docker:
      - image: node:latest
    working_directory: /myApp

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      # - run:
      #     name: make my working directory
      #     command: mkdir app

      # - run:
      #     name: change directory
      #     command: cd app
      - run:
          name: show all directories
          command: ls

      - run:
          name: show directory
          command: pwd

      - run:
          name: install dependencies
          command: npm install

      - persist_to_workspace:
          root: /myApp
          paths:
            - ./**

  deploy:
    executor: docker-executor
    steps:
      - attach_workspace:
          at: /myApp
      - run:
          name: list all directories
          command: ls
      - run:
          name: run the project
          command: npm start
      # - run:
      #     name: run the project
      #     command: npm start

      # - run:
      #     name: test the project
      #     command: npm test

      # - run:
      #     name: test the context
      #     command: echo $NAME
workflows:
  build_and_test:
    jobs:
      - build
      - deploy:
          requires:
          - build
