version: 2.1

jobs:
  build:
    docker:
      - image: node:latest
    steps:
      - run:
          name:
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
