version: 2.1

executors:
  docker-executor:
    docker:
      - image: node:latest
    working_directory: /app

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: install dependencies
          command: npm install
      - persist_to_workspace:
          root: ~/app
          paths: ./

  deploy:
    executor: docker-executor
    steps:
      - attach_workspace:
        at: ~/app
      - run:
          name: list all directories
          command: ls
      - run:
          name: run the project
          command: npm start
      # - run:
      #     name: run the project
      #     command: npm start

      # - run:
      #     name: test the project
      #     command: npm test

      # - run:
      #     name: test the context
      #     command: echo $NAME
workflows:
  build_and_test:
    jobs:
      - build
      - deploy
