version: 2.1

jobs:
  build:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run:
          name: install dependencies
          command: npm install jest

      - run:
          name: run the project
          command: npm start

      - run:
          name: test the project
          command: npm test
workflows:
  build_and_test:
    jobs:
      - build
